Avoid compiling programs with invalid 'main' funcs
Co-authored-by: Max Larsson <maxslarsson@gmail.com>

diff --git a/hooks/prepare-commit-msg b/hooks/prepare-commit-msg
--- a/hooks/prepare-commit-msg
+++ b/hooks/prepare-commit-msg
@@ -1,29 +1,30 @@
 #!/bin/sh
 
-if ! cargo test; then
+
+abort_commit() {
     printf "\n"
-    echo "Some tests failed; aborting commit"
+    echo "Aborting commit."
+    printf "\n\n"
+    echo "REASON FOR ABORTING COMMIT: $1"
     exit 1
+}
+
+if ! cargo build; then
+    abort_commit "cargo build failed"
+fi
+
+if ! cargo test; then
+    abort_commit "cargo test failed"
 fi
 
 # -D warnings means deny warnings; docs must build with no warnings
 
 if ! RUSTDOCFLAGS="-D warnings" cargo doc --no-deps; then
-  printf "\n"
-  echo "Docs don't build correctly; aborting commit"
-  exit 1
-fi
-
-if ! cargo build; then
-    printf "\n"
-    echo "Couldn't build; aborting commit"
-    exit 1
+    abort_commit "cargo doc failed"
 fi
 
 for FLICK_SRC_FILE in examples/*.fl; do
-  if ! target/debug/flick $FLICK_SRC_FILE; then
-    printf "\n"
-    echo "$FLICK_SRC_FILE does not compile; aborting commit"
-    exit 1
-  fi
+    if ! target/debug/flick $FLICK_SRC_FILE; then
+        abort_commit "$FLICK_SRC_FILE does not compile; aborting commit"
+    fi
 done
