Add extern global statements and fix some bugs
Co-authored-by: Thomas Breydo <thomasbreydo@users.noreply.github.com>

diff --git a/hooks/prepare-commit-msg b/hooks/prepare-commit-msg
--- a/hooks/prepare-commit-msg
+++ b/hooks/prepare-commit-msg
@@ -13,3 +13,9 @@ if ! RUSTDOCFLAGS="-D warnings" cargo doc --no-deps; then
   echo "Docs don't build correctly; aborting commit"
   exit 1
 fi
+
+if ! cargo build && target/debug/flick examples/*.fl; then
+  printf "\n"
+  echo "Some programs don't compile; aborting commit"
+  exit 1
+fi
